apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "service-discovery-handler.name" . }}
  labels:
{{- include "service-discovery-handler.labels" . | indent 4 }}
    app: {{ template "service-discovery-handler.name" . }} 
  annotations:
{{- include "service-discovery-handler.helm-annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
