# chat-server configuration 

# global:
  # pullSecret: ""
  # registry:
    # url: "armdocker.rnd.ericsson.se"
    # imagePullSecret: IfNotPresent

imageCredentials:
   # pullSecret:
  chatserver:
    image:
      name: chat-server
      tag: 1.0.0
    repoPath: "proj-5g-bsf" #"proj-ldc/common_base_os"
    registry:
      url: # overrides global registry url
      imagePullPolicy: # overrides global image pull policy

updateStrategy:
  type: RollingUpdate

service:
  chatserver:
    name: "chat-server"
    replicas: 5
    port: "8080"
    targetPort: "8080"

resources:
  chatserver:
    requests:
      memory: "50Mi"
      cpu: "20m"
      ephemeral-storage:
    limits:
      memory: "100Mi"
      cpu: "50m"
      ephemeral-storage:
      
labels: {}

jvm:
  parameters:
    chatserver: "-server -XX:+ErrorFileToStderr -XX:+UseG1GC -XX:MaxRAMPercentage=80"
