# service-discovery-handler configuration 

# global:
  # pullSecret: ""
  # registry:
    # url: "armdocker.rnd.ericsson.se"
    # imagePullSecret: IfNotPresent

imageCredentials:
   # pullSecret:
  sdhandler:
    image:
      name: service-discovery-handler
      tag: 1.0.0
    repoPath: "proj-5g-bsf" #"proj-ldc/common_base_os"
    registry:
      url: # overrides global registry url
      imagePullPolicy: # overrides global image pull policy

updateStrategy:
  type: RollingUpdate

service:
  sdhandler:
    name: "service-discovery-handler"
    replicas: 1
    port: "8080"
    targetPort: "8080"

resources:
  sdhandler:
    requests:
      memory: "50Mi"
      cpu: "20m"
      ephemeral-storage:
    limits:
      memory: "100Mi"
      cpu: "50m"
      ephemeral-storage:
      
labels: {}

jvm:
  parameters:
    sdhandler: "-server -XX:+ErrorFileToStderr -XX:+UseG1GC -XX:MaxRAMPercentage=80"
