#Copyright 2022 Intracom Tel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "service-registry.name" . }}-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "service-registry.labels" . | indent 4 }}
    app: {{ template "service-registry.name" . }}
  annotations:
{{- include "service-registry.helm-annotations" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list