# service-discovery-handler configuration 

# global:
  # pullSecret: ""
  # registry:
    # url: ""
    # imagePullSecret: IfNotPresent

imageCredentials:
   # pullSecret:
  sdhandler:
    image:
      name: sd-handler
      tag: 0.0.1
    repoPath: "evolgr"
    registry:
      url: "armdockerhub.rnd.ericsson.se" # overrides global registry url
      imagePullPolicy: # overrides global image pull policy

updateStrategy:
  type: RollingUpdate

service:
  sdhandler:
    name: "sd-handler"
    replicas: 1
    port: "8080"
    targetPort: "8080"

resources:
  sdhandler:
    requests:
      memory: "50Mi"
      cpu: "500m"
      ephemeral-storage:
    limits:
      memory: "150Mi"
      cpu: "1000m"
      ephemeral-storage:
      
labels: {}