apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "chat-server.name" . }}
  labels:
{{- include "chat-server.labels" . | indent 4 }}
    app: {{ template "chat-server.name" . }} 
  annotations:
{{- include "chat-server.helm-annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
